---
services:
  code-server:
    image: ghcr.io/linuxserver/code-server:latest
    container_name: code-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code.entrypoints=web"
      - "traefik.http.routers.code.rule=Host(`code.${DOMAIN_NAME}`)"
      - "traefik.http.routers.code-secure.tls=true"
      - "traefik.http.routers.code-secure.entrypoints=websecure"
      - "traefik.http.routers.code-secure.rule=Host(`code.${DOMAIN_NAME}`)"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=${PASSWORD} #optional
      #- HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code.${DOMAIN_NAME} #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
      - PWA_APPNAME=code-server #optional
    networks:
      - backend
    volumes:
      - /mnt/fast/appdata/code-server/config:/config
      - /mnt/fast/appdata:/appdata #Added so server can be used to edit config files remotely
    ports:
      - 8443:8443
    restart: unless-stopped
networks:
  backend:
    external: true
  frontend:
    external: true
